server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://trolley.proxy.rlwy.net:36263/railway?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: qgUtgJyvdvMQXdNYcFYlgAGYyVRxcjWr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: huh2378r7hf02DFWU0FDVgcgvdS28LOP029k3KƠDJdWKD323rdfj321sdavbkSV
    expiration-ms: 86400000
